services:
  - type: web
    name: retinascan-frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    env:
      - key: NODE_VERSION
        value: 18
    routes:
      - type: rewrite
        source: /*
        destination: /index.html